# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161229_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followed', through='api.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
