# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161229_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='activityfollow',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
        migrations.AddField(
            model_name='activityfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(related_name='followed', through='api.ActivityFollow', to='api.Activity'),
        ),
    ]
