# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170809_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=40, null=True, upload_to=b'./static/api/default.ico', width_field=40),
        ),
    ]
