# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170809_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('source', models.CharField(max_length=8)),
                ('feedId', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location', models.CharField(max_length=64)),
                ('text', models.TextField(max_length=256)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('fromFacebook', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
