# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feedId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='userId',
            new_name='user',
        ),
    ]
