# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170924_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='location',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.CharField(choices=[(b'Native', b'Native'), (b'Facebook', b'Facebook')], max_length=8),
        ),
    ]
