# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171030_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discover_distance',
            field=models.DecimalField(decimal_places=3, default=9999.999, max_digits=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='api.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
