# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20171218_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='discover_common_activities',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='discover_age_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='discover_age_min',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='user',
            name='discover_common_activities',
            field=models.ManyToManyField(to='api.Activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='discover_distance',
            field=models.DecimalField(decimal_places=3, default=9999.999, max_digits=7),
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
