# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171218_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discover_common_activities',
        ),
    ]
