# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_user_discover_common_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discover_age_max',
            field=models.IntegerField(default=61),
        ),
    ]
