# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20171229_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='location',
        ),
        migrations.AddField(
            model_name='feed',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Activity'),
        ),
    ]
