# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-30 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171230_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
