# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_feed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='api.Activity'),
        ),
    ]
