# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180107_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discoverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
