# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='type',
            field=models.CharField(choices=[(b'Like', b'Like'), (b'Comment', b'Comment')], default=b'Like', max_length=8),
        ),
    ]
