# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-27 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_reaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('datetime',)},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email',)]),
        ),
    ]
